server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payment_db}
    username: ${DB_USER:aegis}
    password: ${DB_PASSWORD:aegis}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
services:
  fraud: ${FRAUD_SERVICE_URL:http://localhost:8083}
  merchant: ${MERCHANT_SERVICE_URL:http://localhost:8082}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
